# Vector

## Konsep Eigenvalue dan Eigenvector
Kata “eigen” berasal dari Bahasa Jerman yang artinya “asli” atau “karakteristik”. Dengan kata lain, nilai eigen menyatakan nilai karakteristik dari sebuah matriks yang berukuran n x n.

Konsep mengenai Eigenvalue dan Eigenvector ini diaplikasikan dalam berbagai bidang ilmu seperti statistika, ekonomi, komputer dan ilmu lainnya. Berikut adalah definisinya:

> Jika A adalah matriks n x n, maka vektor tak-nol $x$ di dalam $R^n$ dinamakan eigenvector dari A jika $Ax$ adalah perkalian suatu skalar $λ$ dengan $x$, yaitu $Ax=λx$. Skalar $λ$ dinamakan eigenvalue dari A dan $x$ dikatakan vektor eigen yang bersesuaian dengan $λ$.

Berikut adalah cara menghitung eigenvalue dan eigenvector secara manual:
- Diberikan sebuah matriks A berukuran n x n. Vektor eigen dan nilai eigen dari matriks A dihitung sebagai berikut:
> Ax = λx

  > IAx = λIx (kalikan kedua ruas dengan I = matriks identitas)

  > Ax = λIx

  > (λI-A)x = 0

  > x = 0 adalah solusi trivial dari (λI-A)x = 0. Agar memiliki solusi tidak-nol, maka haruslah det(λI-A) = 0 (persamaan ini disebut persamaan karakteristik dari matriks A, dan akar-akar persamaan tersebut, yaitu λ, dinamakan akar-akar karateristik atau nilai-nilai eigen).


### Matriks 2x2

$ A =
 \begin{bmatrix}
  3 & 0\\
  8 & -1
 \end{bmatrix}
$

#### *Menentukan Eigenvalue*
$λI-A=$
$λ
 \begin{bmatrix}
  1 & 0\\
  0 & 1
 \end{bmatrix}
$
$-
 \begin{bmatrix}
  3 & 0\\
  8 & -1
 \end{bmatrix}
$
$=
 \begin{bmatrix}
  λ & 0\\
  0 & λ
 \end{bmatrix}
$
$-
 \begin{bmatrix}
  3 & 0\\
  8 & -1
 \end{bmatrix}
$
$=
 \begin{bmatrix}
  λ-3 & 0\\
  -8 & λ+1
 \end{bmatrix}
$

$det(λI-A)=0$
$→
 \begin{vmatrix}
  λ-3 & 0\\
  -8 & λ+1
 \end{vmatrix}
$
$=0$
$→ (λ-3)(λ+1) = 0$
$→ λ_1=3$ dan $λ_2=-1$

#### *Menentukan Eigenvector*
$(λI-A)x = 0$
$→
 \begin{bmatrix}
  λ-3 & 0\\
  -8 & λ+1
 \end{bmatrix}
$
$
 \begin{bmatrix}
  x_1\\
  x_2
 \end{bmatrix}
$
$=
 \begin{bmatrix}
  0\\
  0
 \end{bmatrix}
$

> **Untuk λ=3**
$→
 \begin{bmatrix}
  0 & 0\\
  -8 & 4
 \end{bmatrix}
$
$
 \begin{bmatrix}
  x_1\\
  x_2
 \end{bmatrix}
$
$=
 \begin{bmatrix}
  0\\
  0
 \end{bmatrix}
$
$→ -8x_1 + 4x_2 = 0 → 8x_1 = 4x_2 → x_1 = ½ x_2$
$→ Solusi: x_1 = ½ t, x_2 = t, t ϵ R$

Berarti, eigenvectornya adalah
$=
 \begin{bmatrix}
  \frac12 t\\
  t
 \end{bmatrix}
$

> **Untuk λ=-1**
$→
 \begin{bmatrix}
  -4 & 0\\
  -8 & 0
 \end{bmatrix}
$
$
 \begin{bmatrix}
  x_1\\
  x_2
 \end{bmatrix}
$
$=
 \begin{bmatrix}
  0\\
  0
 \end{bmatrix}
$

> Selesaikan dengan Eliminasi Gauss:
$
 \begin{bmatrix}
  -4 & 0 & 0\\
  -8 & 0 & 0
 \end{bmatrix}
$
$R1/(-4)$
$
 \begin{bmatrix}
  1 & 0 & 0\\
  -8 & 0 & 0
 \end{bmatrix}
$
$R2+8R1$
$
 \begin{bmatrix}
  1 & 0 & 0\\
  0 & 0 & 0
 \end{bmatrix}
$
$→ Solusi: x_1 = 0, x_2 = t, t ϵ R$

Berarti, eigenvectornya adalah
$=
 \begin{bmatrix}
  0\\
  t
 \end{bmatrix}
$


### Matriks 3x3

$ A =
 \begin{bmatrix}
  3 & -2 & 0\\
  -2 & 3 & 0\\
  0 & 0 & 5
 \end{bmatrix}
$

#### *Menentukan Eigenvalue*
$λI-A=$
$
 \begin{bmatrix}
  λ & 0 & 0\\
  0 & λ & 0\\
  0 & 0 & λ
 \end{bmatrix}
$
$-
 \begin{bmatrix}
  3 & -2 & 0\\
  -2 & 3 & 0\\
  0 & 0 & 5
 \end{bmatrix}
$
$=
 \begin{bmatrix}
  λ-3 & -2 & 0\\
  -2 & λ-3 & 0\\
  0 & 0 & λ-5
 \end{bmatrix}
$

$det(λI-A)=0$
$→
 \begin{vmatrix}
  λ-3 & -2 & 0\\
  -2 & λ-3 & 0\\
  0 & 0 & λ-5
 \end{vmatrix}
$
$=0$

Gunakan baris ke-3 sebagai acuan:

$0
 \begin{vmatrix}
  -2 & 0\\
  λ-3 & 0
 \end{vmatrix}
$
$-0
 \begin{vmatrix}
  λ-3 & 0\\
  -2 & 0
 \end{vmatrix}
$
$+(λ-5)
 \begin{vmatrix}
  λ-3 & -2\\
  -2 & λ-3
 \end{vmatrix}
$
$=0$

$(λ - 5)( (λ - 3)(λ - 3) - 4) = 0$

$(λ - 5) (λ2 - 6λ + 5) = 0$

$(λ - 5) (λ - 5)(λ - 1) = 0$

$→ λ_1=5$ dan $λ_2=1$


#### *Menentukan Eigenvector*

$(λI-A)x = 0$
$→
 \begin{bmatrix}
  λ-3 & -2 & 0\\
  -2 & λ-3 & 0\\
  0 & 0 & λ-5
 \end{bmatrix}
$
$
 \begin{bmatrix}
  x_1\\
  x_2\\
  x_3
 \end{bmatrix}
$
$=
 \begin{bmatrix}
  0\\
  0\\
  0
 \end{bmatrix}
$

> **Untuk λ=5**
$→
 \begin{bmatrix}
  2 & 2 & 0\\
  2 & 2 & 0\\
  0 & 0 & 0
 \end{bmatrix}
$
$
 \begin{bmatrix}
  x_1\\
  x_2\\
  x_3
 \end{bmatrix}
$
$=
 \begin{bmatrix}
  0\\
  0\\
  0
 \end{bmatrix}
$

> Selesaikan dengan Eliminasi Gauss:

*Matrix Augmented*

$
 \begin{bmatrix}
  2 & 2 & 0\\
  2 & 2 & 0\\
  0 & 0 & 0
 \end{bmatrix}
$
$R1/2$
$
 \begin{bmatrix}
  1 & 1 & 0\\
  2 & 2 & 0\\
  0 & 0 & 0
 \end{bmatrix}
$
$R2-2R1$
$
 \begin{bmatrix}
  1 & 1 & 0\\
  0 & 0 & 0\\
  0 & 0 & 0
 \end{bmatrix}
$

diperoleh persamaan: $x_1 + x_2 = 0 → x_1 = -x_2$

misal $x_2 = s, x_3 = t$, maka $x_1 = -s $

Berarti, eigenvectornya adalah
$=
 \begin{bmatrix}
  -s\\
  s\\
  t
 \end{bmatrix}
$
$=s
 \begin{bmatrix}
  -1\\
  1\\
  0
 \end{bmatrix}
$
$+t
 \begin{bmatrix}
  0\\
  0\\
  1
 \end{bmatrix}
$
> **Untuk λ=1**
$→
 \begin{bmatrix}
  -2 & 2 & 0\\
  2 & -2 & 0\\
  0 & 0 & -4
 \end{bmatrix}
$
$
 \begin{bmatrix}
  x_1\\
  x_2\\
  x_3
 \end{bmatrix}
$
$=
 \begin{bmatrix}
  0\\
  0\\
  0
 \end{bmatrix}
$

> Selesaikan dengan Eliminasi Gauss:

*Matrix Augmented*

$
 \begin{bmatrix}
  -2 & 2 & 0 & 0\\
  2 & -2 & 0 & 0\\
  0 & 0 & -4 & 0
 \end{bmatrix}
$
$R1/(-2)$
$
 \begin{bmatrix}
  1 & -1 & 0 & 0\\
  2 & -2 & 0 & 0\\
  0 & 0 & -4 & 0
 \end{bmatrix}
$
$R2-2R1$
$
 \begin{bmatrix}
  1 & -1 & 0 & 0\\
  0 & 0 & 0 & 0\\
  0 & 0 & -4 & 0
 \end{bmatrix}
$
$R3/(-4)$
$
 \begin{bmatrix}
  1 & -1 & 0 & 0\\
  0 & 0 & 0 & 0\\
  0 & 0 & 1 & 0
 \end{bmatrix}
$

diperoleh persamaan: $x_3 = 0, x_1 - x_2 = 0 → x_1 = x_2$

misal $x_2 = t$, maka $x_1 = t$

Berarti, eigenvectornya adalah
$=
 \begin{bmatrix}
  t\\
  t\\
  0
 \end{bmatrix}
$


## Contoh menghitung eigenvalue dan eigenvector menggunakan numpy

In [1]:
import numpy as np
from numpy import linalg as LA

A = np.array([[3,0],[8,-1]])
print(A)
a, b = LA.eig(A)
print(a)
print(np.round(b))

[[ 3  0]
 [ 8 -1]]
[-1.  3.]
[[0. 0.]
 [1. 1.]]


In [ ]:
B = np.array([[3,-2,0],[-2,3,0],[0,0,5]])
print(B)
c, d = LA.eig(B)
print(c)
print(np.round(d))

[[ 3 -2  0]
 [-2  3  0]
 [ 0  0  5]]
[5. 1. 5.]
[[ 1.  1.  0.]
 [-1.  1.  0.]
 [ 0.  0.  1.]]


## Implementasi dari Eigen Value dan Eigen Vektor.


### Principal Component Analysis (PCA)

Secara intuitif, PCA adalah prosedur transformasi yang mengubah matriks data dengan fitur-fitur yang mungkin berkorelasi menjadi sekumpulan variabel yang tidak berkorelasi linier yang disebut komponen utama. Setiap komponen utama merupakan kombinasi linier dari fitur asli ($PCᵢ = Xϕᵢ$, di sini $PCᵢ$ adalah singkatan dari komponen utama ke-i) dan memperhitungkan varian terbesar yang mungkin terjadi serta ortogonal terhadap komponen sebelumnya (jika $i ≠ j, PCᵢ ⋅ PCⱼ = 0$).

Mengingat matriks fitur X berbentuk n x p yang berada di tengah , yaitu rata-rata kolom telah dikurangi dan sekarang sama dengan nol, kasus penggunaan PCA yang umum meliputi:
- Pengurangan dimensi: temukan perkiraan dimensi yang lebih rendah dari X bentuk n x k (di mana k jauh lebih kecil dari p ) dengan tetap mempertahankan sebagian besar varian, sebagai langkah pra-pemrosesan untuk klasifikasi atau visualisasi.
- Rekayasa fitur: membuat representasi baru dari X dengan p fitur yang tidak berkorelasi linier.
- Pembelajaran tanpa pengawasan: ekstrak k komponen utama (di mana k seringkali jauh lebih kecil dari p). Pahami kumpulan data dengan melihat bagaimana fitur asli berkontribusi terhadap faktor-faktor ini.

Secara konseptual, penting untuk diingat bahwa PCA adalah pendekatan analisis data multivariat dan EVD dan SVD adalah metode numerik.

In [2]:
# Implementasi secara EVD
import numpy as np

def pcaEVD(X):
    n, p = X.shape
    X_centered = X - X.mean(axis=0)
    C = (X_centered.T @ X_centered) / (n - 1)
    e_vals, e_vecs = np.linalg.eig(C)
    
    idx = e_vals.argsort()[::-1]
    e_vals = e_vals[idx]
    e_vecs = e_vecs[:, idx]
    
    return (X_centered @ e_vecs), e_vals, e_vecs

x = np.array([[3,0],[8,-1]])

components, eigenvalues, eigenvectors = pcaEVD(x)

rounded_components = np.round(components)
rounded_eigenvalues = np.round(eigenvalues)
rounded_eigenvectors = np.round(eigenvectors)

print("Components:\n", rounded_components)
print("Eigenvalues:\n", rounded_eigenvalues)
print("Eigenvectors:\n", rounded_eigenvectors)

Components:
 [[-3. -0.]
 [ 3.  0.]]
Eigenvalues:
 [13.  0.]
Eigenvectors:
 [[ 1.  0.]
 [-0.  1.]]


In [6]:
# Implementasi secara SVD
import numpy as np

def pcaSVD(X):
    # Center X and get covariance matrix C
    n, p = X.shape
    X_centered = X - X.mean(axis=0)

    # SVD
    u, sigma, vt = np.linalg.svd(X_centered, full_matrices=False)

    # Return principal compnents and eigenvalues to calculate the portion of sample variance explained
    return (X_centered @ vt.T), (sigma**2) / (n-1)


x = np.array([[3,0],[8,-1]])

com, ev = pcaSVD(x)

rounded_components = np.round(com)
rounded_eigenvalues = np.round(ev)

print("Components:\n", rounded_components)
print("Eigenvalues:\n", rounded_eigenvalues)

Components:
 [[-3.  0.]
 [ 3.  0.]]
Eigenvalues:
 [13.  0.]
